[[fields]]
path = "service_uuid"
type = "string"
required = true
force_new = true

[[fields]]
path = "username"
type = "string"
required = true
force_new = true

[[outputs]]
path = "service_uuid"
type = "string"

[[outputs]]
path = "username"
type = "string"

[[outputs]]
path = "arn"
type = "string"
