[[fields]]
path = "name"
type = "string"
required = true

[[fields]]
path = "region"
type = "string"
required = true
force_new = true

[[fields]]
path = "configured_status"
type = "string"
required = true

[[fields]]
path = "termination_protection"
type = "boolean"

[[fields]]
path = "networks"
type = "array"

[[fields.items]]
path = "name"
type = "string"
required = true

[[fields.items]]
path = "type"
type = "string"
required = true

[[fields.items]]
path = "family"
type = "string"
required = true

[[fields.items]]
path = "uuid"
type = "string"

[[outputs]]
path = "uuid"
type = "string"

[[outputs]]
path = "name"
type = "string"

[[outputs]]
path = "region"
type = "string"

[[outputs]]
path = "configured_status"
type = "string"

[[outputs]]
path = "operational_state"
type = "string"

[[outputs]]
path = "endpoints"
type = "array"

[[outputs]]
path = "endpoints.*.domain_name"
type = "string"

[[outputs]]
path = "endpoints.*.type"
type = "string"
